version: '2.3'
services:
  opencv:
    tty: true # https://stackoverflow.com/questions/44884719/exited-with-code-0-docker
    image: nivrattituito/opencv-dnn-4.5.5-static-ubuntu-1804:latest
    container_name: nivrattituito_opencv
    volumes:
      - ./workspace:/workspace
    user: root
    build:
      context: build
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: 18.04
        OPENCV_VERSION: 4.5.5
    ipc: host
    restart: unless-stopped     # or "always"
